//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBases.Integration.DataBaseQueries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlScripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlScripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataBases.Integration.DataBaseQueries.SqlScripts", typeof(SqlScripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO author (name, login, email) VALUES (@author_name, @login, @email);.
        /// </summary>
        internal static string AddAuthor {
            get {
                return ResourceManager.GetString("AddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO project (name) VALUES (@project_name);.
        /// </summary>
        internal static string AddProject {
            get {
                return ResourceManager.GetString("AddProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO session (session_key, build_number) VALUES (@session_key, @build_number).
        /// </summary>
        internal static string AddSession {
            get {
                return ResourceManager.GetString("AddSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM test WHERE id = @test_id;.
        /// </summary>
        internal static string DeleteTestById {
            get {
                return ResourceManager.GetString("DeleteTestById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO test (name, status_id, method_name, project_id, session_id, start_time, end_time, env, browser, author_id) VALUES (@name, @status_id, @method_name, @project_id, @session_id, @start_time, @end_time, @env, @browser, @author_id);.
        /// </summary>
        internal static string InsertFullTest {
            get {
                return ResourceManager.GetString("InsertFullTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT author.id FROM author WHERE author.name = @author_name;.
        /// </summary>
        internal static string SelectAuthorIdByName {
            get {
                return ResourceManager.GetString("SelectAuthorIdByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT project.id FROM project WHERE project.name = @project_name;.
        /// </summary>
        internal static string SelectProjectIdByName {
            get {
                return ResourceManager.GetString("SelectProjectIdByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT session.id FROM session WHERE session.session_key = @session_key;.
        /// </summary>
        internal static string SelectSessionIdBySessionKey {
            get {
                return ResourceManager.GetString("SelectSessionIdBySessionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM test WHERE test.session_id = @session_id;.
        /// </summary>
        internal static string SelectTestBySessionId {
            get {
                return ResourceManager.GetString("SelectTestBySessionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM test WHERE test.id LIKE @random LIMIT @limit;.
        /// </summary>
        internal static string SelectTestsByRandomId {
            get {
                return ResourceManager.GetString("SelectTestsByRandomId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE test SET env = &apos;Updated&apos; WHERE id = @test_id;.
        /// </summary>
        internal static string UpdateEnvTest {
            get {
                return ResourceManager.GetString("UpdateEnvTest", resourceCulture);
            }
        }
    }
}
